Dependencies fix
prooph/micro-do pull request #9
Opened 2017-03-10 04:45 UTC by hlogeon

Hi! I've been playing around with your solution but clashed some problems during installation. Maybe I'm doing something wrong but when I try to follow your installation instructions, `composer install` fails with errors like:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpspec/prophecy dev-patch-1 as 1.6.2 exists as phpspec/prophecy[v1.1.2, v1.4.0, dev-master, 1.7.x-dev, v1.0.0, v1.0.0-BETA1, v1.0.0-BETA2, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.1.0, v1.1.1, v1.2.0, v1.2.1, v1.3.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0, v1.6.1, v1.6.2, v1.7.0, 1.6.x-dev] but these are rejected by your constraint.
```

And there are some other issues in composer.json files which leads to errors. I just replaced previously specified versions by the newer and MORE STABLE versions of the packages. I hope it can help to someone like me who wants just to play with your solution without any modifications.

2017-03-10 08:44 UTC, prolic requested changes

2017-03-10 08:44 UTC, prolic commented on service/user-read/composer.json
> +    "prooph/event-store": "^7.0",
Revert this please

2017-03-10 08:44 UTC, prolic commented on service/user-read/composer.json
> +    "prooph/pdo-event-store": "^1.0"
Revert this please

2017-03-10 08:44 UTC, prolic commented on service/user-read/composer.json
> +    "phpspec/prophecy": "1.7.0",
Should be ^1.7

2017-03-14 02:29 UTC, hlogeon commented on service/user-read/composer.json
> +    "prooph/event-store": "^7.0",
Did you check it? If I revert it it's just stop working, I think there is not such tags in your repos anymore.

2017-03-14 02:29 UTC, hlogeon commented on service/user-read/composer.json
> +    "prooph/pdo-event-store": "^1.0"
Did you check it? If I revert it it's just stop working, I think there is not such tags in your repos anymore.

2017-03-14 02:30 UTC, hlogeon commented on service/user-read/composer.json
> +    "phpspec/prophecy": "1.7.0",
True, got it

2017-03-14 13:10 UTC, prolic commented on service/user-read/composer.json
> +    "prooph/event-store": "^7.0",
There is no 7.0 final release yet. Use 7.0-dev, if that breaks it, we need to update micro-do.

2021-03-22 23:03 UTC, closed without merging